num1 = int(input("შეიყვანეთ პირველი რიცხვი: "))  
num2 = int(input("შეიყვანეთ მეორე რიცხვი: "))
num3 = int(input("შეიყვანეთ მესამე რიცხვი: "))
num4 = int(input("შეიყვანეთ მეოთხე რიცხვი: "))

print(num1 + num2 + num3 + num4)  
print(num1 - num2)
print(num1 * num2)
print(num1 / num2)
print(num1 // num2)
print(num1 % num2)
print(num1 ** 3)

print(num1 == num2)
print(num1 > num2)
print(num1 < num2)
print(num1 >= num2)
print(num1 <= num2)
print(num1 != num2)
