num1 = int(input("please enter number here: "))
num2 = int(input("please  enter second  number here: "))
print(num1 + num2)
print(num1 - num2)
print(num1 / num2)
print(num1 * num2)
print(num1 = num2)
print(num1 == num2)