print("luca guarnera")
print("luka lomsadze")
print("ნიკა ფეტელავა")
print("giorgitarielashvil")
print("giorgi melidze")
print("nika datishvili")
print("nia chanturidze")
print("levani maricashvili")
print("მათე საპანაძე")
print("luka navroziashvili")
print("luka gurgenidze")
print("daniel abramidze")
print("beridze mate")
print("გობრონ წითლაური")