input("please write youre father's name : " )
input("please write youre mother's name : " )
input("please write youre sister_brather's name: " )
input("please write youre grandfather's name: " )
input("please write youre grandmother's name: " )